### ISSUE TITLE
[Bug] copy paste is broken when appflowly is runing

### ISSUE THREAD

**Issue by yodatak** [AppFlowy-IO/AppFlowy#1472]
### Bug Description

When appflowly is up copy paste is broken for my windows 10 20H2.

### How to Reproduce

0.0.6.2 and try to copy paste

### Expected Behavior

Copy paste is not broken in windows

### Operating System

Windows 10

### AppFlowy Version(s)

0.0.6.2

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/1550

I tried to fix this issue in the above PR and verified it on Windows 11. Will fix the Linux issue once I get my Linux computer.

**Comment by annieappflowy** [comment]
@LucasXu0 status?

**Comment by LucasXu0** [comment]
It has been fixed.

**Comment by i5hi** [comment]
Still having this issue with the latest release 0.2.5 on a Mac M1.

**Comment by i5hi** [comment]
Only when copy pasting from external windows into Appflowy. 

Copy pasting within AppFlowy is fine.

**Comment by i5hi** [comment]
also seems to be when copying from RAW file format on GitHub

**Comment by matheoxz** [comment]
I'm having this issue too. Before interacting with code blocks the copy/paste from other windows seems normal, but after interacting with a code block, it just doesn't work.

**Comment by EvenTopland** [comment]
I'm having pasting issues on Mac M1 too.
It happens when i:
- Copy a title and tries to paste it somewhere else
- Copy an image and tries to paste it somewhere else
When the paste is not successful, it only writes "v", so it seems like it ignores the CMD+V and only writes the V.
However, sometimes the past work if I press it repeatedly
