### ISSUE TITLE
[Bug] MacOS 13.1 (M1) says it can't verify application and can't execute application

### ISSUE THREAD

**Issue by uvulpos** [AppFlowy-IO/AppFlowy#1724]
### Bug Description

<img width="277" alt="Screenshot 2023-01-18 at 15 34 31" src="https://user-images.githubusercontent.com/53957681/213199310-5392da63-ef6f-4b63-95d7-7fccabc11ea7.png">

### How to Reproduce

Installation via brew, release zip and dmp File

### Expected Behavior

Execute application without warning

### Operating System

MacOS 13.1 Ventura (M1 Arm)

### AppFlowy Version(s)

0.0.9.1

### Additional Context

you probably need to sign it with an apple developer account

**Comment by uvulpos** [comment]
Yes, checked your release action and there is no step to sign your Application. Maybe this helps: https://github.com/marketplace/actions/import-code-signing-certificates

**Comment by annieappflowy** [comment]
Done

**Comment by uvulpos** [comment]
Hi @annieappflowy,
thank you for taking this issue into release 0.2.9, but this fix is apparently available in 0.2.10 or isn't working properly. Get the same issue 😬

**Comment by uvulpos** [comment]
I did not read it up, I was just assuming it, that it would be v0.2.10. But the point is, I installed 0.2.9, and I still got a signing error. So for me the error is not fixed yet

https://github.com/AppFlowy-IO/AppFlowy/assets/53957681/6c04ffde-c1e0-44b6-9438-be881a7e3a7a
