### ISSUE TITLE
[FR] Toggle headings

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3035]
### Description

I'd like to toggle headings (H1, H2, and H3)

### Impact

Toggle list users

**Comment by annieappflowy** [comment]
Press cmd/ctrl + option/alt + T to expand or close all toggles in a toggle list.

Related to https://github.com/AppFlowy-IO/AppFlowy/issues/1078

**Comment by Ahad-patel** [comment]
@annieappflowy This issue is already solved by @LucasXu0 in this PR => #6598

**Comment by lynrayy** [comment]
Why closed? It STILL NOT WORKING
![image](https://github.com/user-attachments/assets/bd9b7ed7-a24b-4636-8a7e-3d2588c5720f)
![image](https://github.com/user-attachments/assets/606961cb-2988-431a-ba5c-c25ed1d190d7)

**Comment by lynrayy** [comment]
Still not working
https://youtu.be/eW9fd4zNSUQ

**Comment by Ahad-patel** [comment]
Hey @lynrayy, 
The toggle headings is developed as a seperate feature, it does not replace the original headings, hope this helps.


https://github.com/user-attachments/assets/58b8bc61-1532-4539-87be-8d463132af2d

**Comment by lynrayy** [comment]
> The toggle headings is developed as a seperate feature, it does not replace the original headings, hope this helps.

You should make it as it made in notion. Very intuitive and convinient despite this one.
At least it SHOULD be in quick floating menu. For example, i am NOT using commands at all! And a lot of casual people too

**Comment by annieappflowy** [comment]
@lynrayy , it works the same as Notion, to be honest. What's missing is the Turn Into menu in the toolbar when you select text.

**Comment by annieappflowy** [comment]
@lynrayy , We'll add toggles to the toolbar, but the toggle feature itself is already supported. This is why this issue was closed.

**Comment by lynrayy** [comment]
> it works the same as Notion, to be honest. What's missing is the Turn Into menu in the toolbar when you select text.

Ok checked out, notion has 2 types of headers too. But! Both types located in floating toolbar so i used by intuition before and didn't noticed that it really 2 different types

Also there is header duplication issue
https://youtu.be/UeX_XvDbZyo

And... When you clicking below the header, text won't be inside of header, it will be outside header block
https://youtu.be/1RRPxbsjf0Q

**Comment by annieappflowy** [comment]
@lynrayy , please check out the videos:

https://github.com/user-attachments/assets/70e457fb-6e67-4cd1-8189-ed1c4849643d

https://github.com/user-attachments/assets/3f67616e-0e27-4403-b609-a96086b1dfcc

"Also there is header duplication issue" - not apples to apples (check out my second video)

I don't have access to your second video.

I acknowledge that Turn Into is not in the float toolbar, which we'll add later.

**Comment by lynrayy** [comment]
> I don't have access to your second video.

Yeah. Forgot to select avaiability. Fixed seconds ago

**Comment by annieappflowy** [comment]
> > I don't have access to your second video.
> 
> Yeah. Forgot to select avaiability. Fixed seconds ago

This is something we should support. As a workaround, press Enter after completing the toggle heading to start a new line inside.
