### ISSUE TITLE
[Bug] RTL related issues

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3414]
### Bug Description

- [ ] some blocks don't support RTL, heading, toggle list, outline, and code block.
- [ ] the selection area in RTL layout is overflow
<img width="1057" alt="Screenshot 2023-09-15 at 17 36 44" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/7599b210-d493-47a2-9de0-d9c2bf1b709d">
- [ ] wrap the layout options into the same parent option.
- [ ] improve texts: layout option and text direction
- [ ] context menu overflow in RTL mode.
- [ ] option menu overflow in RTL 
<img width="272" alt="Screenshot 2023-09-15 at 17 46 08" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/eb7630d2-8d7b-4fd6-aba2-545230b6edc4">
mode.

### How to Reproduce

run the code in the latest main branch

### Expected Behavior

none

### Operating System

All Platform

### AppFlowy Version(s)

0.3.2

**Comment by zoli** [comment]
Please assign this to me.

**Comment by annieappflowy** [comment]
we can close this issue now? @zoli , @LucasXu0

**Comment by zoli** [comment]
> we can close this issue now? @zoli , @LucasXu0

"option menu overflow in RTL" is Resolved. I couldn't reproduce "the selection area in RTL layout is overflow". Also about "wrap the layout options into the same parent option" and "improve texts: layout option and text direction" I think they are left to new design?

**Comment by rileyhawk1417** [comment]
@zoli would you say that this issue still needs to be opened or its been resolved?

**Comment by zoli** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/3286303?s=64&amp;u=6ee80a92cc56bacf5590992d45776bd74d6164a1&amp;v=4">@zoli](https://github.com/zoli?rgh-link-date=2025-01-26T14%3A13%3A15.000Z) would you say that this issue still needs to be opened or its been resolved?

Not sure, Haven't checked it out recently.

**Comment by kareemul** [comment]
Urgent: Lack of RTL support is a deal-breaker for Arabic users 

"Hi AppFlowy Team,

I am a Fedora Linux user and I truly admire the work you've done on this project. However, I must be honest: the lack of RTL (Right-to-Left) support makes the app completely unusable for the Arabic-speaking community.

Currently, text alignment and character rendering are broken, which forces us to look for other alternatives like Obsidian or Anytype, even though we prefer AppFlowy's performance.

Since this is an open-source project, we expect basic accessibility for one of the world's most spoken languages. Please prioritize RTL support in the upcoming editor updates.

Best regards,"
