### ISSUE TITLE
[Bug] Invalid location of the window at launch

### ISSUE THREAD

**Issue by ciseur68** [AppFlowy-IO/AppFlowy#3525]
### Bug Description

At launch, the window of the app goes to its previous location (coordinates) no matter if it is still valid (outside of the screen).

### How to Reproduce

Open AppFlowy, place the window on a secondary monitor, close AppFlowy, disconnect secondary screen and open AppFlowy. The window disappears after a half second outside of the screen.

### Expected Behavior

Stay on the main screen if the last location is outside of the available screens.

### Operating System

Windows 11

### AppFlowy Version(s)

 AppFlowy_0.3.2_windows-x86_64.zip

**Comment by annieappflowy** [comment]
I think this was fixed
Let us know if you still run into this issue

**Comment by ciseur68** [comment]
Hi @annieappflowy, I still run into this issue on 0.4.1.

**Comment by PhilipElonroad** [comment]
Still experienced this issue on 0.4.2 on Windows 10, even after reinstall. Fiddled with different Display Settings, extended / disconnected combinations and got the window back.
