### ISSUE TITLE
Bug with in-app notifications

### ISSUE THREAD

**Issue by abermudez7** [AppFlowy-IO/AppFlowy#5438]
### Bug Description

I have a Win 10 computer, and I use AppFlowy version v0.5.8.
There are several bugs that happen, first one when I insert a grid in a page, I want to provide a notification to remind me the date and time, and I configure it, I accept it and I enter again and it appears as if I had not selected anything, with the word ‘none’.
This problem also happens on my Android 14 phone with the same version of the app.

### How to Reproduce

1) Insert a new grid. 
2) Add a new date property.
3) Select a date.
4) Include the time.
5) Select a reminder.
6) Choose any of the options.
7) OK.
8) Remove the reminder window.
9) Return to step 5. 
And by repeating this step, you can see that the reminder was not saved and even if you enter it again, it is never saved.

### Expected Behavior

The reminder is not saved and even if it is re-entered, it is never saved.

### Operating System

Windows 10 and Android 14

### AppFlowy Version(s)

0.5.8

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/147677108/53cdf25c-7c68-4159-9333-fa6ad51e5111

**Comment by zetashift** [comment]
Same there happening on Linux, Wayland:
- Flatpak version 0.5.8

**Comment by Qurella** [comment]
Similiar problem here:

- Windows 11 & Client Version 0.5.8 connected to selfhosted server
- Creating a new page and date with a reminder sometimes removes the remider itself OR when it stays the upcoming notifications are empty.

**Comment by Xazin** [comment]
This issue could be related to timezones, or a regression. We'll look into it.



> Similiar problem here:
> 
> * Windows 11 & Client Version 0.5.8 connected to selfhosted server
> * Creating a new page and date with a reminder sometimes removes the remider itself OR when it stays the upcoming notifications are empty.

Your scenario is quite different, duplicating a page doesn't duplicate the reminders themselves, so therefore you'll have a non-functioning reminder inside that document. We'll consider how to handle this issue.

**Comment by Qurella** [comment]
Today the reminder settings didn't dissapear even once (had the same problemn as above https://github.com/AppFlowy-IO/AppFlowy/issues/5438#issue-2324571337):

https://github.com/AppFlowy-IO/AppFlowy/assets/59469632/bc472276-8d36-4674-b05c-e5c0bfdd63ff

**Comment by abermudez7** [comment]
Yes, in fact to me the reminder does not give me problem when I put the date directly to the page or home, but it is when I want to configure it from a grid. :(

**Comment by Xazin** [comment]
I've resolved this in the next version, but I'll wait with closing this until we have confirmed it as resolved in 0.6.1 :+1:

**Comment by zetashift** [comment]
> I've resolved this in the next version, but I'll wait with closing this until we have confirmed it as resolved in 0.6.1 👍

I'm on 0.6.4 and it still doesn't work. Same behaviour.
However on a non-cloud/synced instance it does work.

**Comment by annieappflowy** [comment]
I have tested it with v0.6.6, and it works on my macOS.
Can you @zetashift confirm that the issue still persists?

**Comment by zetashift** [comment]
On `v0.6.6` the time is correctly being added(and synced to mobile!), tested on Linux&Wayland and Android.

However, the reminder does not pop up yet on the notifications panel(maybe a separate issue?):
![image](https://github.com/user-attachments/assets/44e1f0b4-7bb4-45db-bcd4-f85a00c39cbd)

**Comment by zetashift** [comment]
On `v0.6.7` doesn't seem to happen anymore!

**Comment by annieappflowy** [comment]
Should be fixed already. Please feel free to reopen
